# Generated by Django 5.0.2 on 2024-02-23 20:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('profile_img', models.ImageField(default='image/defalut.jpg', upload_to='media')),
                ('address', models.CharField(max_length=250)),
                ('profession', models.CharField(choices=[('Student', 'Student'), ('Job', 'Job'), ('Other', 'Other')], max_length=100)),
                ('assosiat_with', models.CharField(blank=True, choices=[('College', 'College'), ('Coaching', 'Coaching'), ('Office', 'Office'), ('Other', 'Other')], max_length=250, null=True)),
                ('college_name', models.CharField(blank=True, max_length=250, null=True)),
                ('coaching_name', models.CharField(blank=True, max_length=250, null=True)),
                ('office_name', models.CharField(blank=True, max_length=250, null=True)),
                ('other', models.CharField(blank=True, max_length=250, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('adhar_card', models.ImageField(blank=True, null=True, upload_to='adhar_card/')),
                ('phone_number', models.CharField(max_length=15)),
                ('father_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_joing', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
