# Generated by Django 5.0.2 on 2024-05-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='description',
        ),
        migrations.AddField(
            model_name='leave',
            name='due',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
