# Generated by Django 5.0.2 on 2024-05-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='total_seat',
            new_name='available_seat',
        ),
    ]
